version: '3'

services:
  flask:
    build: .
    container_name: flask_app
    restart: always
    env_file:
      - .env
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask
